spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  output:
    ansi:
      enabled: always
  config:
    activate:
      on-profile: local

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    groups-order: DESC
    server: http://localhost:8080
    description: Local Server
  paths-to-match: /v1/**

logging:
  config: "classpath:logback-local.xml"
  level:
    # HTTP Request 정보 출력
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    org.springframework.web.reactive.function.client.ExchangeFunctions: debug
    com.trace.id.demo: debug
    org.hibernate.dialect: off
    org.hibernate.type.BasicTypeRegistry: warn

server:
  port: 8080